### ISSUE TITLE
Q: Compatibility issue with playwright 1.4?

### ISSUE THREAD

**Issue by mortelee** [qawolf/playwright-video#135]
Hi

I'm creating UI tests using playwright 1.4 and use your awesome playwright-video package to capture the results of the UI test.
When I call saveVideo I see some typescript  error in my editor. I'm not sure if this is because of using playwright 1.4. Never hurts to ask ;)

![image](https://user-images.githubusercontent.com/1556873/93191151-7d491600-f744-11ea-8946-66eea90ee717.png)

**Comment by jperl** [comment]
@mortelee We are probably going to deprecate this package since Playwright is adding native video recording support. You can try it out in playwright 1.4 https://playwright.dev/#version=v1.4.0&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-videospath

**Comment by mortelee** [comment]
@jperl ok, I like the playwright-video package. 
Let's see if with playwright we get the same functionality (eg: naming videos and multiple browser window support). 
I've tried _videoPath option but nothing is recorded.

**Comment by jperl** [comment]
@mortelee We will update playwright-video to playwright@1.4 and we can see if the video capture gets better with playwright@1.5 before deciding to deprecate playwright-video.

**Comment by jperl** [comment]
@mortelee The new release is based on playright@1.4.1, let me know if you run into any issues.

**Comment by reiinoldo** [comment]
I believe that `playwright-core` dependency was removed. 
Can it be updated to use the `playwright` dependency instead? At least until this package be deprecated.
