### ISSUE TITLE
Not possible to record videos when running tests in parallel

### ISSUE THREAD

**Issue by mortelee** [qawolf/playwright-video#14]
Hi

I'm running playwright scenario's with cucumber-js. One of the cucumber options is to run tests in parallel. When running scenario's in parallel no video captures are created.

Using:
"playwright": "^0.11.1-next.1583993157193",
"playwright-video": "^0.5.0",
"cucumber": "^6.0.5",

Regards

Marco

**Comment by jperl** [comment]
@mortelee Thanks for reporting this issue, it should work in parallel. Do you mind running it with the `DEBUG=playwright-video*` environment variable and including all the logs.

**Comment by mortelee** [comment]
Will keep you up to date. Can be next week unfortanetly

**Comment by flaurida** [comment]
@mortelee just want to confirm you have FFmpeg installed?

**Comment by mortelee** [comment]
I've used "npm i playwright@next playwright-video ffmpeg-static"

**Comment by mortelee** [comment]
In my package.json I've the following debug entry:
"debug": "node --inspect-brk=1337 --nolazy node_modules/cucumber/bin/cucumber-js --tags @debug"

In my launch.json I've added:
"DEBUG": "playwright-video*"
and
"logging": {
    "trace": true,
    "traceResponse": true,
    "engineLogging": true
  }

With this config everything works fine.
When I add --parallel 2 to the debug entry in package.json, the debug session does not do anything . Turning on exceptions breaks in a lot of places but does not make sense to me.

**Comment by mortelee** [comment]
Successful run without parallel option:
[Document1.txt](https://github.com/qawolf/playwright-video/files/4337487/Document1.txt)

**Comment by mortelee** [comment]
I've tried to create a small demo app (based on the code that I already had) to show the problem.
After "npm install" I see that in utils.ts (playwright-video) CRBrowserContext cannot be found.
What am I doing wrong?

I use following package.json

{
  "name": "playwright-test",
  "version": "1.0.0",
  "description": "Trying oyt playwright",
  "main": "index.js",
  "scripts": {
    "build": "npm run lint | exit 0 && tsc",
    "debug": "node --inspect-brk=1337 --nolazy node_modules/cucumber/bin/cucumber-js --tags @debug",
    "dup": "jscpd . --format typescript --format-exts typescript:ts --config ./.jscpd.json",
    "format": "prettier \"**/*.{ts,tsx}\" --write",
    "format:check": "prettier --check \"**/*.{ts,tsx}\"",
    "lint": "eslint --ext ts .",
    "mktestdir": "mkdirp ./test/report && mkdirp ./test/video",
    "test": "npm run build && npm run mktestdir && cucumber-js features/",
    "test:cath": "npm run build && npm run mktestdir && cucumber-js features/ -p cath"
  },
  "keywords": [],
  "author": "",
  "devDependencies": {
    "@types/chai": "^4.1.2",
    "@types/cucumber": "^6.0.1",
    "@types/node": "^13.9.0",
    "@typescript-eslint/eslint-plugin": "^2.22.0",
    "@typescript-eslint/parser": "^2.22.0",
    "chai": "^4.2.0",
    "cucumber": "^6.0.5",
    "cucumber-html-reporter": "^5.1.0",
    "cucumber-pretty": "^6.0.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "ffmpeg-static": "^4.0.1",
    "jscpd": "^2.0.16",
    "mkdirp": "^1.0.3",
    "playwright": "^0.11.1-next.1583993157193",
    "playwright-video": "^0.5.0",
    "prettier": "^1.19.1",
    "typescript": "^3.7.2"
  }
}

**Comment by mortelee** [comment]
Found the problem. Something in my own source code.

**Comment by jperl** [comment]
Glad to hear you figured it out 🙏. Let me know if you run into further issues.
