### ISSUE TITLE
Record video with multiple windows

### ISSUE THREAD

**Issue by louis57** [qawolf/playwright-video#142]
The app I am writing tests, has multiple windows. For example, first I need to login on `MainPage`, click button Edit, then second page `EditPage` will be opened, and the rest of actions happen on second page `EditPage`

I have written method to take video with chromium of the whole test flow from begin to end, but when the EditPage opens, the video is still focused on MainPage. The same goes for screenshot, when test fails on EditPage, the screenshot is still taken on MainPage

Below is part of my code:

```javascript
// definition of take video and take screenshot functions
export async function recordeVideo(page: Page, name: string) {
  return await saveVideo(page, videoDir + name + "_" + Date.now() + ".mp4");
}

// definition of test
beforeAll(async () => {
  browser = await _.getBrowser();
  context = await browser.newContext(_.contextOptions);
  page = await context.newPage();
  capture = await _.recordeVideo(page, "test_video");
  await page.goto(URL, { waitUntil: "networkidle" });
});

describe("E2E Tests", () => {
  // here are all defined test steps, 
 // just example how to handle multiple windows:
const editBtn = await page.$(editButton);

// Get EditPage after clicking button
[editPage] = await Promise.all([
    context.waitForEvent('page')
]);
await editPage.waitForLoadState();
// then the tests go on on editPage
});
```
As I see the problem is, `page` is the input of function `recordeVideo` and `takeScreenshot`, that's why they don't take video or screenshot on `editPage`.

How can I record or take screenshot with multiple windows?

Thanks in advance.

**Comment by dialupdev** [comment]
There's a `followPopups` option available that does what you're describing. https://github.com/qawolf/playwright-video#playwright-videosavevideopage-savepath-options

**Comment by louis57** [comment]
@celeryclub wow, it works. Thanks a lot, This is what I'm looking for.

I have another question, maybe you could help. So, I use this capture option

```js
export async function recordeVideo(page: Page, name: string) {
  return await saveVideo(page, videoDir + name + "_" + Date.now() + ".mp4", { followPopups: true });
}
```
My app is kind of big. I have one testcase, where it has 3 windows: `page` opens `Popup1`, and `Popup1` opens `Popup2` (and the rest happens at `Popup2`)

`page` and `Popup1` are recorded, but `Popup2` is not recorded in video. Could it be that `followPopups` option only follows a direct Popup, not Popup of a Popup?

Thanks.

**Comment by dialupdev** [comment]
Yes that's correct - this is a limitation of this feature. I guess the readme should be updated to reflect that.
