### ISSUE TITLE
Invalid video file

### ISSUE THREAD

**Issue by celeryclub** [qawolf/playwright-video#22]
Hi team. Hope all is well!

I've been testing this out on a project and I'm running into a weird issue. I'm running inside of docker using `qawolf/playwright-ci:v1.0.0`.

My JS looks like this.

```js
import { saveVideo } from 'playwright-video';

describe('marketing/overview', () => {
  it('loads the overview page', async () => {
    const capture = await saveVideo(page, 'videos/marketing/overview.mp4');
    // do some stuff on the page
    await capture.stop();
  });
});
```

I can run the code and everything passes and a video file is even generated, but when I try to open it QuickTime tells me it's invalid.

Do you know why this might be? If not, I can create a more detailed repro if that would be helpful.

Thanks for building this tool! 🙏🏻

**Comment by jperl** [comment]
Does it open with [VLC](https://www.videolan.org/vlc/index.html)?

**Comment by celeryclub** [comment]
Oh it does! Very interesting... do you know why?

**Comment by jperl** [comment]
QuickTime supports a limited amount of video formats / encodings. Whereas VLC supports most valid ones. VLC is my go to player.

**Comment by celeryclub** [comment]
Right on. Thank you for the tip!
