### ISSUE TITLE
Feature request: Abort capture

### ISSUE THREAD

**Issue by celeryclub** [qawolf/playwright-video#23]
Hey again. I have a feature request. In my scenario, I'm saving screenshots (and now videos) only when my tests fail in order to conserve disk space in CI. It'd be nice to have a way to run either `await capture.stop()` or `await capture.abort()` depending on the situation. What do you think about this idea?

**Comment by flaurida** [comment]
Hi @celeryclub a few thoughts:

If you are using this library by itself, you can get the `capture` class instance and call the `stop` method on it (see bottom of README for more details). After that you could delete the file using `fs`. Here is a rough outline:

```
import fs from 'fs';

// ...
const capture = await saveVideo(page, '/tmp/video.mp4');
// your test code
await capture.stop();
fs.unlinkSync('/tmp/video.mp4')
```

Would that solve your issue? If not, please provide more detail on your use case so we can think about next steps.

Thanks for the feedback and suggestion 😊

**Comment by celeryclub** [comment]
Well, yeah. I think you're right. I guess that's really all this function would do anyway. Hah. I guess I was overthinking it. Thank you for the response!

**Comment by flaurida** [comment]
Hi @celeryclub glad that will work for you 😊 keep me posted if you have any issues!
