### ISSUE TITLE
Feature: Multi-tab recording

### ISSUE THREAD

**Issue by celeryclub** [qawolf/playwright-video#24]
Hey team. This tool has been working really well for me. Thanks for building this!

I'm wondering if you'd consider supporting multi-tab recording. Right now if my tests opens another tab, the video still only shows the original tab.

Thanks for your consideration!

**Comment by jperl** [comment]
It records one page by design. If you want to record multiple pages, you can do [`qawolf.register(context)`](https://docs.qawolf.com/docs/api/qawolf/register) and [`qawolf.stopVideos`](https://docs.qawolf.com/docs/api/qawolf/stop_videos).

**Comment by flaurida** [comment]
@celeryclub if you are using this library by itself, you can also create a new video for your new tab. Just pass the new page to `saveVideo`:

```js
const { chromium } = require('playwright');
const { saveVideo } = require('playwright-video');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  await saveVideo(page, '/tmp/video.mp4');
  await page.goto('http://example.org');
  await page.click('a');

const page2 = await context.newPage();
await saveVideo(page2, '/tmp/video2.mp4');

// ...
})();
```

Please let us know if that helps!

**Comment by celeryclub** [comment]
Gotcha. That makes sense. I'm curious if it's possible to switch contexts to match up with whatever the user sees (the active tab) during the video recording, and if that's a feature that you think would be a good addition to this library.

**Comment by jperl** [comment]
Not sure I understand. Are you suggesting to have one video for multiple pages? If so, this is something we thought about when initially building `playwright-video` but its tricky to pull off since different pages can have different viewports.

**Comment by celeryclub** [comment]
Yes exactly. I guess that's true The scenario I'm referring to is clicking a link that opens in a new tab. So in that case, the viewports are the same size.

**Comment by celeryclub** [comment]
Perhaps this behavior could be opt-in considering that it doesn't work for every case? Or do you think it doesn't fit into this library at all?

**Comment by jperl** [comment]
If it works well I think it would be great. Happy to review a PR.
