### ISSUE TITLE
Feature: Use @ffmpeg-installer/ffmpeg instead of ffmpeg-static

### ISSUE THREAD

**Issue by celeryclub** [qawolf/playwright-video#30]
`ffmpeg-static` is licensed as GPL-3.0-or-later, which is a copyleft license. This prevents it from being included in any commercial applications. `@ffmpeg-installer/ffmpeg` is LGPL-2.1, which is somewhat more lenient. There's a good summary here: http://answers.google.com/answers/threadview/id/439136.html.

Happy to make this change if you're ok with it.

**Comment by jperl** [comment]
Sounds good to me. Thank you for all of your contributions.

**Comment by jperl** [comment]
FWIW, playwright-video does not include `ffmpeg-static` but rather references it as a peerDependency which is optional. I am curious if `GPL` makes a distinction for that.

**Comment by celeryclub** [comment]
That's true @jperl. But if users (like me!) want to record video in their non-docker dev environment while not using a license forbidden by their (my) company, there was no easy way to do that before.

**Comment by jperl** [comment]
Totally, thanks again for the PR.
