### ISSUE TITLE
Bug: Frames not being written correctly (maybe?)

### ISSUE THREAD

**Issue by celeryclub** [qawolf/playwright-video#32]
After https://github.com/qawolf/playwright-video/pull/31 I started seeing this at the end of my logs. I haven't yet determined if the frames are actually written incorrectly, but something is off. Going to dig in further.

```sh
pw-video:VideoWriter write -1 frames for duration -0.03s +3s
pw-video:VideoWriter write 9 frames for duration 0.373s +0ms
pw-video:VideoWriter write -2 frames for duration -0.074s +1ms
pw-video:VideoWriter write 4 frames for duration 0.172s +0ms
pw-video:VideoWriter write 12 frames for duration 0.494s +0ms
pw-video:VideoWriter write 5 frames for duration 0.181s +0ms
pw-video:VideoWriter write 0 frames for duration 0s +0ms
pw-video:VideoWriter write 15 frames for duration 0.592s +0ms
pw-video:VideoWriter write 2 frames for duration 0.094s +0ms
pw-video:VideoWriter write -4 frames for duration -0.154s +11ms
pw-video:VideoWriter write 8 frames for duration 0.336s +0ms
```

**Comment by celeryclub** [comment]
Repro tip: the script I saw this on was navigating between pages very quickly. Goto page, check for selector, repeat.

**Comment by jperl** [comment]
They won't actually be written since its `for (let i = 0; i < numFrames; i++) {`.

My suspicion is that the negative frames are between `SortedFrameQueue` emits.

**Comment by jperl** [comment]
Found the issue, I was using received instead of timestamp.

**Comment by jperl** [comment]
@celeryclub This should be fixed in `playwright-video@1.0.2` let me know if you are still encountering an issue.

**Comment by celeryclub** [comment]
Thanks for the quick turnaround @jperl! This fixes the issue for me.

**Comment by jperl** [comment]
Ok great. Sorry about that.
