### ISSUE TITLE
feature: Use ffmpeg from path

### ISSUE THREAD

**Issue by mxschmitt** [qawolf/playwright-video#42]
It would be nice if it would detect / use as a fallback the ffmpeg which which is in the path if there is one. So `apt-get install ffmpeg` would work out of the box.

In the end the user has three ways of using it:
- custom FFMPEG_PATH
- @ffmpeg-installer/ffmpeg 
- fallback of ffmpeg which is in the path

Current workaround:

```bash
export FFMPEG_PATH=$(which ffmpeg)
```

**Comment by celeryclub** [comment]
I like that idea. 👍

**Comment by mxschmitt** [comment]
Probably we can then use [this package](https://www.npmjs.com/package/lookpath) to detect if its in the path since [hasbin](https://www.npmjs.com/package/hasbin) seems not that well maintained / has TS bindings.
